import "./globals.css";
import type { Metadata } from "next";
import { Header } from "./_Components/Header/Header";
import { Footer } from "./_Components/Footer/Footer";

import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({
  weight: ['400', '500', '700', '800', '900'],
  subsets: ['latin'] 
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en" suppressHydrationWarning>

      <head>
        {/* Import des styles CSS */}
        <link
          rel="stylesheet"
          href="https://cdn.lineicons.com/4.0/lineicons.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/4.2.0/remixicon.css"
          integrity="sha512-OQDNdI5rpnZ0BRhhJc+btbbtnxaj+LdQFeh0V9/igiEPDiWE2fG+ZsXl0JEH+bjXKPJ3zcXqNyP4/F/NegVdZg=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
        {/* Google Fonts */}
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>

    
      <body className={montserrat.className}>  
            <Header />
            {children}
            <Footer />
      </body>
    
    </html>
  );
}
